name    'thilina-apimanager'
version '0.2.0'
source 'https://github.com/wso2/Puppet'
author 'Thilina Piyasundara'
license 'Apache License Version 2.0'
summary 'WSO2 APIManager puppet module'
description 'WSO2 AM 1.6.0 version puppet module'
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
dependency 'thilina/wso2base'
dependency 'thilina/elb'
