name    'thilina-wso2base'
version '1.2.0'
source ''
author 'Thilina Piyasundara'
license 'Apache License, Version 2.0'
summary 'This module is to use as a base for any WSO2 modules'
description ''
project_page ''

## Add dependencies, if any:
# dependency 'username/name', '>= 1.2.0'
